import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout-wrapper";
import { MainMenu } from "@/components/main-menu";
import { currentUser } from "@/lib/currentAuth";
import { MeButtons } from "./(root)/_components/me-buttons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: {
    absolute: "", // menimpa semua value yang lain
    default: "Tamiweb | Next + Ts", // default untuk page ini dan childnya
    template: "%s | Tamiweb", // nilai dinamis tergantung childnya
  },
  description: "Description Tamiweb",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.className}`}>
        <MainMenu user={user} />
        <MeButtons />
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
