import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout-wrapper";
import { MainMenu } from "@/components/main-menu";
import { currentUser } from "@/lib/currentAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tamiweb | Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <MainMenu user={user} />
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
